//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class childGuardian
    {
        public int ChildGuardianId { get; set; }
        public int GuardianId { get; set; }
        public int ChildId { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte[] TRTimestamp { get; set; }
    
        public virtual ccChild ccChild { get; set; }
        public virtual user user { get; set; }
    }
}
