//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provider()
        {
            this.attendances = new HashSet<attendance>();
            this.attendanceExpecteds = new HashSet<attendanceExpected>();
            this.provider1 = new HashSet<provider>();
            this.providerUsers = new HashSet<providerUser>();
        }
    
        public int ProviderId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PrimaryContactUserId { get; set; }
        public Nullable<int> HeadProviderId { get; set; }
        public bool IsHub { get; set; }
        public int UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public byte[] TRTimestamp { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Locality { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Postcode { get; set; }
        public string CountryCode { get; set; }
        public string PhonePrefix { get; set; }
        public string PhoneNumber { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendanceExpected> attendanceExpecteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider> provider1 { get; set; }
        public virtual provider provider2 { get; set; }
        public virtual refState refState { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<providerUser> providerUsers { get; set; }
    }
}
