//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.attendances = new HashSet<attendance>();
            this.attendanceExpecteds = new HashSet<attendanceExpected>();
            this.ccChilds = new HashSet<ccChild>();
            this.childGuardians = new HashSet<childGuardian>();
            this.providerUsers = new HashSet<providerUser>();
            this.providerUsers1 = new HashSet<providerUser>();
            this.providers = new HashSet<provider>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public byte[] TRTimestamp { get; set; }
        public string EmailAddress { get; set; }
        public string StatusCd { get; set; }
        public string LogonId { get; set; }
        public string Password { get; set; }
        public string Comments { get; set; }
        public string Title { get; set; }
        public string SecondName { get; set; }
        public string OtherNames { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Locality { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Postcode { get; set; }
        public string CountryCode { get; set; }
        public string PhonePrefix { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> ValidFromDate { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendanceExpected> attendanceExpecteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ccChild> ccChilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<childGuardian> childGuardians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<providerUser> providerUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<providerUser> providerUsers1 { get; set; }
        public virtual refState refState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider> providers { get; set; }
    }
}
